stages:
  - build
  - deploy

variables:
  GET_SOURCES_ATTEMPTS: 2

build:
  image: node:14-alpine
  stage: build
  cache:
    paths:
      - .yarn-cache/
  artifacts:
    paths:
      - artifact.tar.gz
    expire_in: 2 weeks
    exclude:
      - .yarn-cache/**
  before_script:
    - yarn config set cache-folder "$(pwd)/.yarn-cache"
  script:
    - yarn install
    - yarn build
    - rm -rf node_modules
    - yarn install --production
    - rm -rf src .git yarn.lock tsconfig.json .eslintrc .gitlab-ci.yml .gitignore
    - mv .yarn-cache /tmp/yarn-cache
    - tar -czf /tmp/artifact.tar.gz .
    - mv /tmp/artifact.tar.gz .
    - mv /tmp/yarn-cache ./.yarn-cache

Production:
  image: alpine
  stage: deploy
  environment:
    name: production
    url: https://api.best-service.no
  before_script:
   - apk add openssh-client
   - eval $(ssh-agent -s)
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
  script:
   - scp -o StrictHostKeyChecking=no artifact.tar.gz bestservice@webhost.ironlions.fi:~/domains/api.best-service.no/
   - >
     ssh -o StrictHostKeyChecking=no bestservice@webhost.ironlions.fi "
       cd ~/domains/api.best-service.no/;
       rm -rf temp && mkdir temp;
       tar zxf artifact.tar.gz -C temp;
       rm -rf artifact.tar.gz node_modules dist package.json;
       mv temp/* .;
       rm -rf temp;
       touch tmp/restart.txt;
     "
  #when: manual
  #only:
  # - master
  dependencies:
    - build
